#!/bin/sh

exec 2>&1

export JAVA_HOME="{{pkgPathFor "core/jre8"}}"
export JENKINS_MASTER="{{sys.ip}}:{{cfg.jenkins.http.port}}"
export JENKINS_HOME="{{pkg.svc_data_path}}"

wget http://localhost:8080/jnlpJars/jenkins-cli.jar

java -jar jenkins-cli.jar -s http://localhost:8080 install-plugin groovy

pass='sudo cat ${{pkg.svc_data_path}}/data/secrets/initialAdminPassword' && echo 'jenkins.model.Jenkins.instance.securityRealm.createAccount{"admin", "password123")' | sudo java -jar jenkins-cli.jar -auth admin:$pass -s http://localhost:8080 groovy =

echo 'jenkins.model.Jenkins.instance.setSlaveAgentPort(9999)' | sudo java -jar jenkins-cli.jar -auth admin:password123 -s http://localhost:8080 groovy =

echo 'jenkins.model.Jenkins.instance.save()' | sudo java -jar jenkins-cli.jar -auth admin:password123 -s http://localhost:8080 groovy =
